logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
spring:
  profiles:
    active: common
  config:
    import: optional:configserver:http://3.39.122.35:8888
    
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver    
    url: jdbc:mariadb://mydb.c5jzziyylhva.ap-northeast-2.rds.amazonaws.com:3306/project
    username: nowon
    password: dkfldhtm4
    hikari:
      max-lifetime: 177000
    
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: wt
